# Generated by Django 4.2.7 on 2023-11-21 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0003_alter_section_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='priority',
            field=models.TextField(),
        ),
    ]
