# Generated by Django 4.2.7 on 2023-11-18 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0003_alter_section_priority'),
        ('task', '0002_alter_task_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='section.section'),
        ),
    ]
