# Generated by Django 4.2.7 on 2023-11-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_task_priority_alter_task_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
